package report

import (
	"fmt"
	"strings"

	"github.com/plexusone/pipelineconductor/pkg/model"
)

// CheckMarkdownFormatter generates Markdown reports for check results.
type CheckMarkdownFormatter struct{}

// Format generates a Markdown report from check results.
func (f *CheckMarkdownFormatter) Format(result *model.CheckResult) ([]byte, error) {
	var sb strings.Builder

	// Header
	sb.WriteString("# Workflow Compliance Report\n\n")
	sb.WriteString(fmt.Sprintf("**Reference:** %s@%s | **Scanned:** %d repos | **Compliance:** %.1f%%\n\n",
		result.Config.RefRepo, result.Config.RefBranch,
		result.Summary.TotalRepos, result.Summary.ComplianceRate))
	sb.WriteString(fmt.Sprintf("**Generated:** %s | **Duration:** %dms\n\n",
		result.Timestamp, result.ScanDurationMs))

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Status | Count |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Fully Compliant | %d |\n", result.Summary.CompliantRepos))
	sb.WriteString(fmt.Sprintf("| Partial | %d |\n", result.Summary.PartialRepos))
	sb.WriteString(fmt.Sprintf("| Non-Compliant | %d |\n", result.Summary.NonCompliant))
	sb.WriteString(fmt.Sprintf("| Skipped | %d |\n", result.Summary.Skipped))
	sb.WriteString(fmt.Sprintf("| Errors | %d |\n", result.Summary.Errors))
	sb.WriteString("\n")

	// By Language
	if len(result.Summary.ByLanguage) > 0 {
		sb.WriteString("### By Language\n\n")
		sb.WriteString("| Language | Total | Compliant | Rate |\n")
		sb.WriteString("|----------|-------|-----------|------|\n")
		for _, lang := range result.Summary.ByLanguage {
			sb.WriteString(fmt.Sprintf("| %s | %d | %d | %.1f%% |\n",
				lang.Language, lang.TotalRepos, lang.CompliantRepos, lang.ComplianceRate))
		}
		sb.WriteString("\n")
	}

	// Configuration
	sb.WriteString("## Configuration\n\n")
	if len(result.Config.Orgs) > 0 {
		sb.WriteString(fmt.Sprintf("- **Organizations:** %s\n", strings.Join(result.Config.Orgs, ", ")))
	}
	if len(result.Config.Users) > 0 {
		sb.WriteString(fmt.Sprintf("- **Users:** %s\n", strings.Join(result.Config.Users, ", ")))
	}
	sb.WriteString(fmt.Sprintf("- **Languages:** %s\n", strings.Join(result.Config.Languages, ", ")))
	sb.WriteString(fmt.Sprintf("- **Strict Mode:** %v\n", result.Config.Strict))
	sb.WriteString("\n")

	// Repositories by compliance level
	f.writeReposByLevel(&sb, result, model.ComplianceLevelNone, "Non-Compliant Repositories")
	f.writeReposByLevel(&sb, result, model.ComplianceLevelPartial, "Partially Compliant Repositories")
	f.writeReposByLevel(&sb, result, model.ComplianceLevelFull, "Fully Compliant Repositories")

	// Skipped and Error repos
	f.writeSkippedRepos(&sb, result)
	f.writeErrorRepos(&sb, result)

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by [PipelineConductor](https://github.com/plexusone/pipelineconductor)*\n")

	return []byte(sb.String()), nil
}

func (f *CheckMarkdownFormatter) writeReposByLevel(sb *strings.Builder, result *model.CheckResult, level, title string) {
	repos := filterReposByLevel(result.Repos, level)
	if len(repos) == 0 {
		return
	}

	sb.WriteString(fmt.Sprintf("## %s\n\n", title))

	for _, repo := range repos {
		f.writeRepoDetail(sb, repo)
	}
}

func (f *CheckMarkdownFormatter) writeRepoDetail(sb *strings.Builder, repo model.RepoCheckResult) {
	icon := complianceIcon(repo.ComplianceLevel)
	sb.WriteString(fmt.Sprintf("### %s %s\n\n", icon, repo.FullName))
	sb.WriteString(fmt.Sprintf("**Languages:** %s | **Level:** %s\n\n",
		strings.Join(repo.Languages, ", "), repo.ComplianceLevel))

	// Workflow check table
	if len(repo.RequiredWorkflows) > 0 {
		sb.WriteString("| Workflow | Present | Reusable | Match |\n")
		sb.WriteString("|----------|---------|----------|-------|\n")
		for _, wf := range repo.RequiredWorkflows {
			present := "❌"
			if wf.Present {
				present = "✅"
			}
			reusable := "No"
			if wf.UsesReusable {
				reusable = "Yes"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				wf.WorkflowType, present, reusable, wf.MatchType))
		}
		sb.WriteString("\n")

		// Show filename mismatch warnings
		var mismatches []model.WorkflowCheck
		for _, wf := range repo.RequiredWorkflows {
			if wf.FilenameMismatch && wf.Present {
				mismatches = append(mismatches, wf)
			}
		}
		if len(mismatches) > 0 {
			sb.WriteString("**⚠️ Filename Mismatches:**\n\n")
			for _, wf := range mismatches {
				sb.WriteString(fmt.Sprintf("- `%s`: expected `%s`, found `%s`\n",
					wf.WorkflowType, wf.ExpectedFilename, wf.ActualFilename))
			}
			sb.WriteString("\n")
		}
	}

	// Missing workflows
	if len(repo.Missing) > 0 {
		sb.WriteString("**Missing:**\n\n")
		for _, m := range repo.Missing {
			sb.WriteString(fmt.Sprintf("- %s `%s` (%s severity): %s\n",
				severityIcon(m.Severity), m.WorkflowType, m.Severity, m.Description))
		}
		sb.WriteString("\n")
	}
}

func (f *CheckMarkdownFormatter) writeSkippedRepos(sb *strings.Builder, result *model.CheckResult) {
	var skipped []model.RepoCheckResult
	for _, repo := range result.Repos {
		if repo.Skipped {
			skipped = append(skipped, repo)
		}
	}

	if len(skipped) == 0 {
		return
	}

	sb.WriteString("## Skipped Repositories\n\n")
	for _, repo := range skipped {
		sb.WriteString(fmt.Sprintf("- **%s**: %s\n", repo.FullName, repo.SkipReason))
	}
	sb.WriteString("\n")
}

func (f *CheckMarkdownFormatter) writeErrorRepos(sb *strings.Builder, result *model.CheckResult) {
	var errors []model.RepoCheckResult
	for _, repo := range result.Repos {
		if repo.Error != "" {
			errors = append(errors, repo)
		}
	}

	if len(errors) == 0 {
		return
	}

	sb.WriteString("## Repositories with Errors\n\n")
	for _, repo := range errors {
		sb.WriteString(fmt.Sprintf("- **%s**: %s\n", repo.FullName, repo.Error))
	}
	sb.WriteString("\n")
}

func filterReposByLevel(repos []model.RepoCheckResult, level string) []model.RepoCheckResult {
	var filtered []model.RepoCheckResult
	for _, repo := range repos {
		if repo.ComplianceLevel == level && !repo.Skipped && repo.Error == "" {
			filtered = append(filtered, repo)
		}
	}
	return filtered
}

func complianceIcon(level string) string {
	switch level {
	case model.ComplianceLevelFull:
		return "✅"
	case model.ComplianceLevelPartial:
		return "🟡"
	case model.ComplianceLevelNone:
		return "❌"
	default:
		return "❓"
	}
}

func severityIcon(severity string) string {
	switch severity {
	case model.SeverityLevelHigh:
		return "🔴"
	case model.SeverityLevelMedium:
		return "🟠"
	case model.SeverityLevelLow:
		return "🔵"
	default:
		return "⚪"
	}
}
