name: TypeScript CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ts-ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ts-ci.yaml'
  workflow_dispatch:

jobs:
  ci:
    uses: grokify/.github/.github/workflows/ts-ci.yaml@main
